=head1 NAME

Shipwright::Manual::Glossary - Glossary for Shipwright

=head1 DESCRIPTION

=head2 distribution

What is imported into a Shipwright repository; e.g. a package from cpan.
Normally, A Shipwright repository generally has more than one distribution, or
dist for short, in it.

=head2 repository

the backend, where all stuff lives, e.g. metadata, sources, etc..
Currently, SVN, SVK and FS(file system) are supported.

=head2 vessel

Shipwright's final product; i.e. what is produced after running C<shipwright
build>.

=head1 SEE ALSO

L<Shipwright::Manual::Tutorial>, L<Shipwright::Manual::UsingFlags>, L<Shipwright::Manual::CustomizeBuild>,

=head1 AUTHORS

sunnavy  C<< <sunnavy@bestpractical.com> >>

=head1 LICENCE AND COPYRIGHT

Shipwright is Copyright 2007-2010 Best Practical Solutions, LLC.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.
