=head1 NAME

Shipwright::Tutorial - introduction to Shipwright 

=head1 SYNOPSIS

In this tutorial, we'll create a simple distribution: the L<Acme::Hello> module
from CPAN.

We will use C<svk://__shipwright/hello> as our repository.

=head1 DESCRIPTION

There are three main steps to creating a shipwright distribution.

=head2 1. init

    $ shipwright create -r svk://__shipwright/hello

=head2 2. import

    $ shipwright import -r svk://__shipwright/hello Acme::Hello

Then shipwright will try to download and import L<Acme::Hello> and all its
dependencies.

If you want to skip some dependencies, e.g. L<Locale::Maketext> and
L<Locale::Maketext::Lexicon>, just say C<--skip Locale::Maketext> and C<--skip
Locale::Maketext::Lexicon>.

Run C<shipwright help import> to see more options.

=head2 3. build

    $ shipwright build -r svk://__shipwright/hello

If tests are time-consuming or for some reason unnecessary for your build, you
can add C<--skip-test> to skip them.

Run C<shipwright help build> to see more options.

A log of the above commands can be found in F<docs/tutorial.log>.

=head1 NOTES

=head2 Updating distributions

There are two commands we can use to update a distribution: C<update> and C<import>.

If you would like to just update the distribution source (files in F<dists/>),
use C<update>. It will delete the directory in dists/ and add it again.

The other way is to C<import> the distribution again. This will delete the
corresponding directories in F<dists/> and F<scripts/> and then add new ones. If
you want to update the dependency lists too, just add the C<--overwrite>
option.

=cut
