#!/usr/bin/env perl

my $link = readlink($0);

if (not $link or $link eq '../etc/shipwright-perl-wrapper') {
    my $base = $0;
    my $base_dir = `dirname "$base"`; chomp $base_dir;
    $base_dir=` (cd "$base_dir"; pwd) `; chomp $base_dir;
    my $filename=`basename "$base"`; chomp $filename;
    my $wrapped_dir=`basename "$base_dir"`; chomp $wrapped_dir;
    $ENV{PERL5LIB}="$base_dir/../lib/perl5/site_perl:$base_dir/../lib/perl5:$ENV{PERL5LIB}";
    $ENV{LD_LIBRARY_PATH}="$base_dir/../lib:$ENV{LD_LIBRARY_PATH}";
    $ENV{DYLD_LIBRARY_PATH}="$base_dir/../lib:$ENV{DYLD_LIBRARY_PATH}";
    exec "$base_dir/../@{[$wrapped_dir]}-wrapped/perl", "$base_dir/../@{[$wrapped_dir]}-wrapped/$filename", @ARGV;
} else {
    exec $link, @ARGV;
}

