=head1 NAME

Shipwright::Manual - Shipwright documentation

=head1 DESCRIPTION

This manual is divided into several parts, each covering a specific topic.

=over 4

=item L<Shipwright::Manual::Tutorial>

A simple tutorial that leads through the creation of a simple Shipwright
vessel.

=item L<Shipwright::Manual::CustomizeBuild>

A guide of customizing the build process of individual distributions in a
Shipwright repository.

=item L<Shipwright::Manual::UsingFlags>

A guide of using Shipwright's flags feature.

=item L<Shipwright::Manual::UsingBranches>

A guide of using Shipwright's branches feature.

=item L<Shipwright::Manual::Glossary>

A Glossary of terms relevant to Shipwright and its documentation.

=back

=head1 AUTHORS

sunnavy  C<< <sunnavy@bestpractical.com> >>

=head1 LICENCE AND COPYRIGHT

Shipwright is Copyright 2007-2010 Best Practical Solutions, LLC.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

