=head1 NAME

Shipwright::Tutorial - Introduction to Shipwright 

=head1 SYNOPSIS

In this tutorial, we'll create a simple project(we call it a vessel): The L<Acme::Hello> module from CPAN.  (We love examples with name hello ;))

We will use C<svk://__shipwright/hello> as our repository.

=head1 DESCRIPTION

=head2 1. init

    $ shipwright create -r svk://__shipwright/hello

=head2 2. import

    $ shipwright import -r svk://__shipwright/hello Acme::Hello

Then shipwright will try to download, and import L<Acme::Hello> and all its dependencies.

If you want to skip some deps, e.g. L<Locale::Maketext> and L<Locale::Maketext::Lexicon>,
just say C<--skip Locale::Maketext> and C<--skip Locale::Maketext::Lexicon>.

Run C<shipwright help import> to see more options.

=head2 3. build

    $ shipwright build -r svk://__shipwright/hello

Test is kind of time consuming? you can add C<--skip-test> to skip tests.

Run C<shipwright help build> to see more options.

The log of the above 3 commands can be found in F<docs/tutorial.log>.

=head1 Note

=head2 Updating distributions

There're two commands we can use to update a dist: C<update> and C<import>.

If you'd like to just update the dist source( files in F<dists/> ), use
C<update>. It will delete the directory in dists and add it again.

The other way is to C<import> the dist again.
Techenically, it will delete the corresponding dirs in F<dists/> and
F<scripts/>, then add new ones.  If you want to update dep dists too,
just add C<--overwrite> option.

=cut
