=head1 NAME

Shipwright::Tutorial - Introduction to Shipwright 

=head1 SYNOPSIS

In this tutorial, we'll build a simple project: The L<Acme::Hello> module from
CPAN.  (We love examples with name hello ;))

We will use C<svk://__shipwright/hello> as our repository.

=head1 DESCRIPTION

=head2 1. init

    $ shipwright create -r svk://__shipwright/hello

=head2 2. import

    $ shipwright import -r svk://__shipwright/hello Acme::Hello

Then shipwright will try to download, and import L<Acme::Hello> and all its dependencies.

If you want to skip some deps, e.g. L<Locale::Maketext> and L<Locale::Maketext::Lexicon>,
just say C<--skip Locale::Maketext> and C<--skip Locale::Maketext::Lexicon>.

Run C<shipwright help import> to see more options.

=head2 3. build

    $ shipwright build -r svk://__shipwright/hello

Test is kind of time consuming? you can add C<--skip-test> to skip tests.

Run C<shipwright help build> to see more options.

The log of the above 3 commands can be found in F<docs/tutorial.log>.

=head1 Note

=head2 Updating distributions

If you just want to update a dist (just the dist source itself, instead of
rebuilding or regenerating F<require.yml>), then use the C<update> command,
which will delete that directory in dists and import again.

If not, you can import it again, which will overwrite the old one. 

Techenically, it will delete the corresponding dir in F<dists/> and
F<scripts/>, then add new one.  If you want to overwrite dep dists too,
then use the C<--overwrite> option.

=cut
